[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'duckpunch/vim-python-indent'
on_ft = 'python'

# [[plugins]]
# repo = 'davidhalter/jedi-vim'
# build = 'git submodule update --init'
# on_ft = 'python'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'vim-erlang/vim-erlang-runtime'
on_ft = 'erlang'

[[plugins]]
repo = 'vim-erlang/vim-erlang-skeletons'
on_ft = 'erlang'

[[plugins]]
repo = 'vim-erlang/vim-erlang-compiler'
on_ft = 'erlang'

[[plugins]]
repo = 'vim-erlang/vim-erlang-tags'
on_ft = 'erlang'

[[plugins]]
repo = 'vim-erlang/vim-erlang-omnicomplete'
on_ft = 'erlang'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'keith/swift.vim'
on_ft = 'swift'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'mxw/vim-jsx.git'
on_ft = 'javascript'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = 'javascript'

[[plugins]]
repo = 'gavocanov/vim-js-indent'
on_ft = 'javascript'

[ftplugin]
_ = '''
setl formatoptions-=ro | setl formatoptions+=mMBl
'''

python = '''
setl softtabstop=4
setl shiftwidth=4
setl textwidth=120
setl smarttab
setl expandtab
setl nosmartindent
setl foldmethod=indent
autocmd FileType python setlocal completeopt-=preview
'''

json = '''
let g:vim_json_syntax_conceal = 0
setl conceallevel=0
'''
